spring.application.name=letsTour
spring.datasource.url=jdbc:mysql://localhost:3306/tourismDatabase
spring.datasource.username=springstudent
spring.datasource.password=springstudent
stripe.secret.api.key=${STRIPE_API_KEY}
